version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - langtranslate
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - langtranslate
    depends_on:
      - backend

networks:
  langtranslate:
    driver: bridge
